version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: "app"
    ports:
      - "9091:9091"
    environment:
      - db_url=jdbc:postgresql://db/weather
      - db_user=postgres
      - db_pass=postgres
    depends_on:
      - db