server:
  port: 9091
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${db_url:jdbc:postgresql://localhost:5432/weather}
    username: ${db_user:postgres}
    password: ${db_pass:postgres}
  flyway:
    baseline-on-migrate: true

openWeather:
  appId: ${openWeather_appId:921070dad9367e4b34b002eea4c1b557}
  url: ${openWeather_appId:http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appId}}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
